Repository Sidekick-Poe/Sidekick, pull requests merged in 2025-04, with the labels that each got.

#617 Improved handling of decimal values in non-english languages
  src/Sidekick.Common.Ui/Forms/FormContentEditable.razor
  src/Sidekick.Common.Ui/Forms/FormNumber.razor
  src/Sidekick.Common/Sidekick.Common.csproj
  src/Sidekick.Modules.Trade/Components/Filters/Properties/DoublePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ExtendedAtMax.razor
  src/Sidekick.Wpf/MainWindow.xaml.cs
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
Labels: Type: Bug

#618 Fixed errors persisting across multiple checks
  src/Sidekick.Common.Ui/Errors/ErrorFullScreenBoundary.razor
  src/Sidekick.Common.Ui/Errors/LoggingErrorBoundary.cs
  src/Sidekick.Common.Ui/Errors/SidekickErrorBoundary.razor
  src/Sidekick.Wpf/MainWindow.xaml.cs
  src/Sidekick.Wpf/SidekickBlazorWrapper.razor
Labels: Type: Bug

#619 Add missing keys that could not be used in keybinds.
  src/Sidekick.Common.Platform/Keyboards/KeyboardProvider.cs
Labels: Type: Bug

#622 Added logging to Velopack internally and cleaned up view management
  src/Sidekick.Wpf/App.xaml.cs
  src/Sidekick.Wpf/Services/WpfViewLocator.cs
Labels: Type: Maintenance

#623 Cleaned up Velopack initialization.
  src/Sidekick.Wpf/App.xaml.cs
  src/Sidekick.Wpf/MainWindow.xaml.cs
  src/Sidekick.Wpf/Program.cs
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
Labels: Type: Maintenance

#624 Downgraded from .Net9 to .Net8 after multiple reports of failures. Thanks @VITAMIN
  .github/workflows/tests.yml
  .github/workflows/windows-beta.yml
  .github/workflows/windows-stable.yml
  .run/Publish Sidekick.Protocol to Sidekick.Wpf.run.xml
  .run/Sidekick.Web.run.xml
  .run/Sidekick.Wpf.run.xml
  Dockerfile
  src/Sidekick.Apis.GitHub/Sidekick.Apis.GitHub.csproj
  src/Sidekick.Apis.Poe/Sidekick.Apis.Poe.csproj
  src/Sidekick.Apis.Poe2Scout/Sidekick.Apis.Poe2Scout.csproj
  src/Sidekick.Apis.PoeNinja/Sidekick.Apis.PoeNinja.csproj
  src/Sidekick.Apis.PoePriceInfo/Sidekick.Apis.PoePriceInfo.csproj
  src/Sidekick.Apis.PoeWiki/Sidekick.Apis.PoeWiki.csproj
  src/Sidekick.Common.Blazor/Sidekick.Common.Blazor.csproj
  src/Sidekick.Common.Database/Sidekick.Common.Database.csproj
  src/Sidekick.Common.Interprocess/Sidekick.Common.Interprocess.csproj
  src/Sidekick.Common.Platform/Sidekick.Common.Platform.csproj
  src/Sidekick.Common.Ui/Sidekick.Common.Ui.csproj
  src/Sidekick.Common.Updater/Sidekick.Common.Updater.csproj
  src/Sidekick.Common/Sidekick.Common.csproj
  src/Sidekick.Modules.Chat/Sidekick.Modules.Chat.csproj
  src/Sidekick.Modules.General/Sidekick.Modules.General.csproj
  src/Sidekick.Modules.Maps/Sidekick.Modules.Maps.csproj
  src/Sidekick.Modules.Trade/Sidekick.Modules.Trade.csproj
  src/Sidekick.Modules.Wealth/Sidekick.Modules.Wealth.csproj
  src/Sidekick.Protocol/Properties/PublishProfiles/Build.pubxml
  src/Sidekick.Protocol/Sidekick.Protocol.csproj
  src/Sidekick.Web/Sidekick.Web.csproj
  src/Sidekick.Wpf/Cloudflare/CloudflareWindow.xaml.cs
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
  tests/Sidekick.Apis.Poe.Tests/Sidekick.Apis.Poe.Tests.csproj
Labels: Type: Maintenance

#626 Use ManagePackageVersionsCentrally (CPM)
  Directory.Packages.props
  src/Sidekick.Apis.GitHub/Sidekick.Apis.GitHub.csproj
  src/Sidekick.Apis.Poe/Sidekick.Apis.Poe.csproj
  src/Sidekick.Apis.Poe2Scout/Sidekick.Apis.Poe2Scout.csproj
  src/Sidekick.Apis.PoeNinja/Sidekick.Apis.PoeNinja.csproj
  src/Sidekick.Apis.PoePriceInfo/Sidekick.Apis.PoePriceInfo.csproj
  src/Sidekick.Apis.PoeWiki/Sidekick.Apis.PoeWiki.csproj
  src/Sidekick.Common.Blazor/Sidekick.Common.Blazor.csproj
  src/Sidekick.Common.Database/Sidekick.Common.Database.csproj
  src/Sidekick.Common.Interprocess/Sidekick.Common.Interprocess.csproj
  src/Sidekick.Common.Platform/Sidekick.Common.Platform.csproj
  src/Sidekick.Common.Ui/Sidekick.Common.Ui.csproj
  src/Sidekick.Common.Updater/Sidekick.Common.Updater.csproj
  src/Sidekick.Common/Sidekick.Common.csproj
  src/Sidekick.Modules.Trade/Sidekick.Modules.Trade.csproj
  src/Sidekick.Modules.Wealth/Sidekick.Modules.Wealth.csproj
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
  tests/Sidekick.Apis.Poe.Tests/Sidekick.Apis.Poe.Tests.csproj
Labels: Type: Maintenance

#631 Fixed overlay appearing behind the game, requiring Alt-Tabbing
  src/Sidekick.Wpf/MainWindow.xaml.cs
Labels: Type: Bug

#632 Fix the interface language not being applied correctly
  src/Sidekick.Common.Blazor/Settings/General/InterfaceLanguageEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common/Localization/IUiLanguageProvider.cs
  src/Sidekick.Common/Localization/UiLanguageProvider.cs
  src/Sidekick.Wpf/Services/WpfViewLocator.cs
Labels: Type: Bug

#633 Don't show Poe2Scout prices if the data isn't populated yet
  src/Sidekick.Apis.Poe2Scout/Poe2ScoutClient.cs
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutComponent.razor
Labels: Type: Bug

#634 Improved general view handling again.
  src/Sidekick.Common.Platform/Windows/DllImport/User32.cs
  src/Sidekick.Wpf/MainWindow.xaml.cs
  src/Sidekick.Wpf/Services/WpfViewLocator.cs
Labels: Type: Maintenance

#636 Fixed the Poe2Scout price graph showing stats in reverse
  src/Sidekick.Apis.Poe2Scout/Api/PriceLogs.cs
  src/Sidekick.Apis.Poe2Scout/Poe2ScoutClient.cs
Labels: Type: Bug

#637 Add missing interface translations and resource keys
  src/Sidekick.Common.Blazor/Home/HomeResources.fr.resx
  src/Sidekick.Common.Blazor/Home/HomeResources.resx
  src/Sidekick.Common.Blazor/Settings/General/LanguageParserEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Blazor/Setup/Setup.fr.resx
  src/Sidekick.Common.Ui/App/AppResources.fr.resx
  src/Sidekick.Common.Updater/Components/Update.fr.resx
  src/Sidekick.Modules.Trade/Localization/TradeResources.fr.resx
  src/Sidekick.Modules.Trade/Localization/TradeResources.ko.resx
  src/Sidekick.Modules.Trade/Localization/TradeResources.resx
  src/Sidekick.Modules.Trade/Settings/PriceCheckItemMinMaxPriceEditor.razor
Labels: Type: Maintenance

#638 Added spear and buckler item classes
  Game Localization.xlsm
  src/Sidekick.Apis.Poe/IItemParser.cs
  src/Sidekick.Apis.Poe/Parser/Headers/HeaderParser.cs
  src/Sidekick.Apis.Poe/Parser/ItemParser.cs
  src/Sidekick.Apis.Poe/StartupExtensions.cs
  src/Sidekick.Common/Game/Languages/ClassLanguage.cs
  src/Sidekick.Common/Game/Languages/IGameLanguage.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageDe.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEn.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEs.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageFr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageJp.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageKr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguagePt.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageRu.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageTh.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageZhTw.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/ArmourParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/WeaponParsing.cs
Labels: Type: Enhancement

#645 Remove self-contained frameworks to reduce installer size
  .github/workflows/windows-beta.yml
  .github/workflows/windows-stable.yml
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
Labels: Type: Maintenance

#646 Further reduce the size of the installer by removing self-contained frameworks
  src/Sidekick.Protocol/Properties/PublishProfiles/Build.pubxml
  src/Sidekick.Protocol/Sidekick.Protocol.csproj
Labels: Type: Maintenance

#649 Added possible chance outcomes to normal rarity items
  src/Sidekick.Apis.Poe2Scout/Api/Poe2ScoutItem.cs
  src/Sidekick.Apis.Poe2Scout/Api/Poe2ScoutPriceLog.cs
  src/Sidekick.Apis.Poe2Scout/IPoe2ScoutClient.cs
  src/Sidekick.Apis.Poe2Scout/Poe2ScoutClient.cs
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutChanceComponent.razor
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutPriceComponent.razor
  src/Sidekick.Modules.Trade/Localization/TradeResources.resx
  src/Sidekick.Wpf/MainWindow.xaml.cs
Labels: Type: Enhancement

#648 Handle missing WebView2 runtime with detailed error message
  src/Sidekick.Wpf/Program.cs
Labels: Type: Maintenance

#647 Improved elemental weapon parsing
  src/Sidekick.Apis.Poe/Modifiers/IInvariantModifierProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/InvariantModifierProvider.cs
  src/Sidekick.Apis.Poe/Parser/ItemParser.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/WeaponDamageProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/IPropertyParser.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyDefinition.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyParser.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/WeaponParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/WeaponParsing.cs
Labels: Type: Bug

#652 Add missing translations, standardize resource calls and remove unused translations
  README.md
  src/Sidekick.Apis.Poe/Bulk/BulkTradeService.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/WeaponDamageProperty.cs
  src/Sidekick.Common.Blazor/Initialization/InitializationResources.fr.resx
  src/Sidekick.Common.Blazor/Initialization/InitializationResources.ko.resx
  src/Sidekick.Common.Blazor/Initialization/InitializationResources.resx
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor
  src/Sidekick.Common.Blazor/Settings/Components/OverlayCloseWithMouseEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/EscapeClosesOverlaysEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/KeyCloseEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/KeyFindItemsEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/LanguageParserEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/RetainClipboardEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.cs
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Blazor/Settings/Wealth/KeyOpenWealthEditor.razor
  src/Sidekick.Common.Blazor/Settings/Wiki/KeyOpenWikiEditor.razor
  src/Sidekick.Common.Platform/Localization/PlatformResources.cs
  src/Sidekick.Common.Platform/Windows/Processes/ProcessProvider.cs
  src/Sidekick.Common.Ui/Errors/LoggingErrorBoundary.cs
  src/Sidekick.Common.Updater/Components/Update.fr.resx
  src/Sidekick.Common.Updater/Components/Update.ko.resx
  src/Sidekick.Common.Updater/Components/Update.razor
  src/Sidekick.Common.Updater/Components/Update.resx
  src/Sidekick.Common/Localization/UiLanguageProvider.cs
  src/Sidekick.Modules.Maps/Settings/KeyOpenMapCheckEditor.razor
  src/Sidekick.Modules.Maps/Settings/MapCheckDangerousRegexEditor.razor
  src/Sidekick.Modules.Trade/Components/Bulk/BulkResult.razor
  src/Sidekick.Modules.Trade/Components/Filters/FilterRange.razor
  src/Sidekick.Modules.Trade/Components/Items/ExtendedAtMax.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemsResult.razor
  src/Sidekick.Modules.Trade/Components/Prices/PricePredictionComponent.razor
  src/Sidekick.Modules.Trade/Localization/TradeResources.cs
  src/Sidekick.Modules.Trade/Localization/TradeResources.fr.resx
  src/Sidekick.Modules.Trade/Localization/TradeResources.ko.resx
  src/Sidekick.Modules.Trade/Localization/TradeResources.resx
  src/Sidekick.Modules.Trade/Prices.razor
  src/Sidekick.Modules.Trade/Settings/KeyOpenPriceCheckEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckPredictionEnabledEditor.razor
Labels: Type: Maintenance

#653 Add BuyMeACoffee button
  src/Sidekick.Common.Blazor/Components/SidekickMenu.razor
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Ui/App/AppBuyMeACoffeeButton.razor
  src/Sidekick.Common.Ui/App/AppResources.fr.resx
  src/Sidekick.Common.Ui/App/AppResources.resx
  src/Sidekick.Common.Ui/wwwroot/images/app/buymeacoffee.png
Labels: Type: Maintenance

#655 Fix Alt keybinds copying the item's text with unnecessary information
  src/Sidekick.Common.Platform/Clipboard/ClipboardProvider.cs
Labels: Type: Bug

#656 Fix Poe2Scout component not showing graph in some cases
  src/Sidekick.Apis.Poe2Scout/Poe2ScoutClient.cs
Labels: Type: Bug

#666 Improve Poe2Scout matching
  src/Sidekick.Apis.Poe2Scout/Poe2ScoutClient.cs
Labels: Type: Bug

#667 Add a setting to hide or show prices from poe.ninja and poe2scout.com
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutChanceComponent.razor
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutPriceComponent.razor
  src/Sidekick.Modules.Trade/Components/Prices/PriceNinjaComponent.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckMarketEnabledEditor.razor
  src/Sidekick.Modules.Trade/Settings/SettingsContent.razor
Labels: Type: Enhancement

#668 Made the fullscreen errors less intrusive
  src/Sidekick.Apis.Poe/Parser/ItemParser.cs
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor
  src/Sidekick.Common.Ui/Alerts/AlertError.razor
  src/Sidekick.Common.Ui/Alerts/AlertInfo.razor
  src/Sidekick.Common.Ui/App/AppClose.razor
  src/Sidekick.Common.Ui/App/AppHome.razor
  src/Sidekick.Common.Ui/App/AppSettings.razor
  src/Sidekick.Common.Ui/Errors/ErrorFullScreenBoundary.razor
  src/Sidekick.Common.Ui/Icons/Icon.razor
  src/Sidekick.Common.Ui/Icons/IconLarge.razor
  src/Sidekick.Common.Ui/Icons/IconMedium.razor
  src/Sidekick.Common.Ui/Icons/IconSmall.razor
  src/Sidekick.Common.Ui/Icons/UiIconSize.cs
  src/Sidekick.Common.Ui/Icons/UiIcons.cs
  src/Sidekick.Common.Ui/Poe/Items/ItemPropertyText.razor
  src/Sidekick.Common.Ui/Tooltips/TooltipHint.razor
  src/Sidekick.Common.Ui/UiIcons.cs
  src/Sidekick.Modules.Maps/MapOverlay.razor
  src/Sidekick.Modules.Trade/Components/Bulk/BulkResult.razor
  src/Sidekick.Modules.Trade/Components/Filters/FilterRange.razor
  src/Sidekick.Modules.Trade/Components/Filters/TradeFilters.razor
  src/Sidekick.Modules.Trade/Components/Options/OpenWebsiteLink.razor
  src/Sidekick.Modules.Trade/Components/Options/ToggleCompactView.razor
Labels: Type: Maintenance

#669 Fixed @last alias not working in some cases
  src/Sidekick.Common.Platform/GameLogs/GameLogProvider.cs
Labels: Type: Bug

#670 Remove unused file and update funding config
  .github/FUNDING.yml
  download-instructions.txt
Labels: Type: Maintenance

#671 No longer calculate quality on spirit property.
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/SpiritProperty.cs
  src/Sidekick.Apis.Poe/Trade/Requests/Filters/StatFilterValue.cs
  src/Sidekick.Common/Game/Items/ItemProperties.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Query/TradeSearchServiceTests.cs
Labels: Type: Bug
