Repository Sidekick-Poe/Sidekick, pull requests merged in 2025-05, with the labels that each got.

#677 Enhance trade filters with a visual cue and a reset button
  src/Sidekick.Common.Blazor/Settings/Chat/ChatCommandEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/UseInvariantForTradeResults.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Ui/Buttons/ButtonPrimary.razor
  src/Sidekick.Common.Ui/Icons/Icon.razor
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/ISettingsService.cs
  src/Sidekick.Common/Settings/SettingsService.cs
  src/Sidekick.Modules.Trade/Components/Filters/TradeFilters.razor
Labels: Type: Enhancement

#673 Improve the feedback of the keybind editors
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor.js
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
Labels: Type: Maintenance

#681 Game language selector now displays languages based on the interface language
  src/Sidekick.Common.Blazor/Settings/General/LanguageParserEditor.razor
Labels: Type: Bug

#680 Minors adjustments to the look of the changelog in the updater
  src/Sidekick.Common.Updater/Components/Update.razor
Labels: Type: Maintenance

#682 Add a way to restore default settings for each settings section
  src/Sidekick.Common.Blazor/Settings/Chat/Chat.razor
  src/Sidekick.Common.Blazor/Settings/Chat/ChatCommandEditor.razor
  src/Sidekick.Common.Blazor/Settings/Components/OverlayCloseWithMouseEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/EscapeClosesOverlaysEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Blazor/Settings/General/KeyCloseEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/KeyFindItemsEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/RetainClipboardEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/SaveWindowPositionsEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/ZoomEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Blazor/Settings/Wiki/KeyOpenWikiEditor.razor
  src/Sidekick.Common.Blazor/Settings/Wiki/PreferredWikiEditor.razor
  src/Sidekick.Common.Blazor/Settings/Wiki/Wiki.razor
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Modules.Maps/Settings/KeyOpenMapCheckEditor.razor
  src/Sidekick.Modules.Maps/Settings/MapCheckDangerousRegexEditor.razor
  src/Sidekick.Modules.Maps/Settings/SettingsContent.razor
  src/Sidekick.Modules.Trade/Settings/KeyOpenPriceCheckEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckAutomaticallySearchCurrencyEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckAutomaticallySearchEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckCurrencyModeEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckDefaultFilterTypeEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckEnableAllFiltersEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckEnableFiltersByRegexEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckItemClassFilter.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckMarketEnabledEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckNormalizeValueEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckPredictionEnabledEditor.razor
  src/Sidekick.Modules.Trade/Settings/SettingsContent.razor
Labels: Type: Enhancement

#683 Add a keybind to open an item in craftofexile.com
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Blazor/Settings/General/KeyOpenInCraftOfExileEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Platform/Clipboard/ClipboardProvider.cs
  src/Sidekick.Common/Platform/IClipboardProvider.cs
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.General/Keybinds/OpenInCraftOfExileHandler.cs
  src/Sidekick.Modules.General/StartupExtensions.cs
Labels: Type: Enhancement

#684 Add web package in releases for cloud gaming
  .github/workflows/windows-stable.yml
  src/Sidekick.Web/Program.cs
  src/Sidekick.Web/Sidekick.Web.csproj
  src/Sidekick.Web/favicon.ico
Labels: Type: Enhancement

#686 Adjust the size of the icons in the appbar
  src/Sidekick.Common.Ui/App/AppBar.razor
  src/Sidekick.Common.Ui/App/AppSettings.razor
Labels: Type: Bug

#687 Fix pre-checked filters not having values if price-checking another item without closing the overlay
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/PseudoFiltersComponent.razor
Labels: Type: Bug

#691 Refactor WpfViewLocator to simplify window management
  src/Sidekick.Wpf/Services/WpfViewLocator.cs
Labels: Type: Maintenance

#693 Fix wrong label shown for map regex in the settings
  src/Sidekick.Modules.Maps/Settings/SettingsContent.razor
Labels: Type: Bug

#694 Add reset and clear buttons to individual settings
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor
  src/Sidekick.Common.Blazor/Settings/Components/SettingCheckboxEditor.razor
  src/Sidekick.Common.Blazor/Settings/Components/SettingKeybindEditor.razor
  src/Sidekick.Common.Blazor/Settings/Components/SettingTextEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/LeagueIdEditor.razor
  src/Sidekick.Common.Blazor/Settings/General/ZoomEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Blazor/Settings/Wiki/PreferredWikiEditor.razor
  src/Sidekick.Common.Ui/Buttons/ButtonIcon.razor
  src/Sidekick.Common.Ui/Forms/FormInput.razor
  src/Sidekick.Common.Ui/Forms/FormSelect.razor
  src/Sidekick.Common.Ui/Icons/UiIcons.cs
  src/Sidekick.Common.Ui/UiClasses.cs
  src/Sidekick.Common.Ui/tailwind.config.js
  src/Sidekick.Modules.Trade/Settings/PriceCheckCurrencyModeEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckDefaultFilterTypeEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckItemClassFilter.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckNormalizeValueEditor.razor
Labels: Type: Enhancement

#700 Fix the bootstrapped dependencies for the web package
  .github/workflows/windows-stable.yml
Labels: Type: Bug

#696 Add item text to the UnparsableException error screen
  src/Sidekick.Apis.Poe/Parser/Headers/HeaderParser.cs
  src/Sidekick.Apis.Poe/Parser/ItemParser.cs
  src/Sidekick.Common.Ui/Errors/ErrorFullScreenBoundary.razor
  src/Sidekick.Common/Exceptions/UnparsableException.cs
Labels: Type: Enhancement

#697 Minor visual adjustments to tooltips and other UI components
  src/Sidekick.Common.Blazor/Home/HomeResources.fr.resx
  src/Sidekick.Common.Blazor/Home/HomeResources.resx
  src/Sidekick.Common.Ui/Forms/FormTextarea.razor
  src/Sidekick.Common.Ui/Tooltips/TooltipLeft.razor
  src/Sidekick.Common.Ui/Tooltips/TooltipRight.razor
  src/Sidekick.Modules.Trade/Components/Prices/Poe2ScoutPriceComponent.razor
  src/Sidekick.Modules.Trade/Components/Prices/PricePredictionComponent.razor
Labels: Type: Maintenance

#695 Add a setting to automatically load more results when scrolling down
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Ui/Utilities/IntersectionObserver.razor
  src/Sidekick.Common.Ui/Utilities/IntersectionObserver.razor.js
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.Trade/Components/Items/ItemsResult.razor
  src/Sidekick.Modules.Trade/Settings/SettingsContent.razor
Labels: Type: Enhancement

#701 Change language code from Jp to Ja for the interface
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageJp.cs
Labels: Type: Bug

#702 Fix a missing interface translation
  src/Sidekick.Modules.Trade/Settings/PriceCheckNormalizeValueEditor.razor
Labels: Type: Bug

#704 Fix regression for alt modifier not being ignored when copying an item text
  src/Sidekick.Common.Platform/Clipboard/ClipboardProvider.cs
Labels: Type: Bug

#698 Add setting to navigate the stash with mouse-wheel
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.ko.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Platform/Keyboards/KeyboardProvider.cs
  src/Sidekick.Common.Ui/tailwind.config.js
  src/Sidekick.Common/Platform/EventArgs/ScrollEventArgs.cs
  src/Sidekick.Common/Platform/IKeyboardProvider.cs
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.General/Keybinds/MouseWheelHandler.cs
  src/Sidekick.Modules.General/StartupExtensions.cs
Labels: Type: Enhancement

#706 Fixed Alt-Codes not working when Sidekick is running
  Directory.Packages.props
  src/Sidekick.Common.Platform/Keyboards/KeyboardProvider.cs
Labels: Type: Bug

#708 Improved input handlers to support scroll wheel inputs.
  Sidekick.sln
  src/Sidekick.Common.Blazor/Home/Home.razor
  src/Sidekick.Common.Platform/Keyboards/KeyboardProvider.cs
  src/Sidekick.Common.Platform/StartupExtensions.cs
  src/Sidekick.Common/Platform/Input/Extensions.cs
  src/Sidekick.Common/Platform/Input/IInputHandler.cs
  src/Sidekick.Common/Platform/Input/KeybindHandler.cs
  src/Sidekick.Common/Platform/Input/ScrollWheelHandler.cs
  src/Sidekick.Common/ServiceCollectionExtensions.cs
  src/Sidekick.Common/SidekickConfiguration.cs
  src/Sidekick.Modules.Chat/Keybinds/ChatKeybindHandler.cs
  src/Sidekick.Modules.Chat/StartupExtensions.cs
  src/Sidekick.Modules.General/Keybinds/CloseOverlayKeybindHandler.cs
  src/Sidekick.Modules.General/Keybinds/CloseOverlayWithEscHandler.cs
  src/Sidekick.Modules.General/Keybinds/FindItemKeybindHandler.cs
  src/Sidekick.Modules.General/Keybinds/MouseWheelHandler.cs
  src/Sidekick.Modules.General/Keybinds/OpenInCraftOfExileHandler.cs
  src/Sidekick.Modules.General/Keybinds/OpenWikiPageKeybindHandler.cs
  src/Sidekick.Modules.General/StartupExtensions.cs
  src/Sidekick.Modules.Maps/Keybinds/OpenMapInfoKeybindHandler.cs
  src/Sidekick.Modules.Maps/StartupExtensions.cs
  src/Sidekick.Modules.RegexHotkeys/Keybinds/RegexHotkeyHandler.cs
  src/Sidekick.Modules.RegexHotkeys/StartupExtensions.cs
  src/Sidekick.Modules.Trade/Keybinds/PriceCheckItemKeybindHandler.cs
  src/Sidekick.Modules.Trade/StartupExtensions.cs
Labels: Type: Maintenance

#707 Add photino project to the solution
  Directory.Packages.props
  Sidekick.sln
  src/Sidekick.Common.Platform/Linux/PackageVerifier.cs
  src/Sidekick.Common.Platform/Linux/ProcessProvider.cs
  src/Sidekick.Common.Platform/StartupExtensions.cs
  src/Sidekick.Common.Ui/App/AppBar.razor
  src/Sidekick.Common.Ui/App/AppResources.resx
  src/Sidekick.Common.Ui/Errors/ConfigurationFlagError.razor
  src/Sidekick.Common.Ui/Forms/FormSelectInline.razor
  src/Sidekick.Common.Ui/Menu/MenuItem.razor
  src/Sidekick.Common/SidekickConfiguration.cs
  src/Sidekick.PhotinoBlazor/Program.cs
  src/Sidekick.PhotinoBlazor/Services/PhotinoBlazorApplicationService.cs
  src/Sidekick.PhotinoBlazor/Services/PhotinoBlazorViewLocator.cs
  src/Sidekick.PhotinoBlazor/Sidekick.PhotinoBlazor.csproj
  src/Sidekick.PhotinoBlazor/SidekickPhotinoBlazorWrapper.razor
  src/Sidekick.PhotinoBlazor/_Imports.razor
  src/Sidekick.PhotinoBlazor/favicon.ico
  src/Sidekick.PhotinoBlazor/wwwroot/.gitignore
  src/Sidekick.PhotinoBlazor/wwwroot/favicon.ico
  src/Sidekick.PhotinoBlazor/wwwroot/index.html
Labels: Type: Maintenance

#710 BETA - Add linux build
  .github/workflows/build-release.yml
  .github/workflows/windows-beta.yml
  src/Sidekick.Common.Updater/AutoUpdater.cs
Labels: Type: Enhancement

#711 Add Flowbite to the project
  src/Sidekick.Common.Ui/.gitignore
  src/Sidekick.Common.Ui/App/AppWrapper.razor
  src/Sidekick.Common.Ui/Sidekick.Common.Ui.csproj
  src/Sidekick.Common.Ui/Styles/main.css
  src/Sidekick.Common.Ui/package-lock.json
  src/Sidekick.Common.Ui/package.json
  src/Sidekick.Common.Ui/tailwind.config.js
  src/Sidekick.PhotinoBlazor/wwwroot/index.html
  src/Sidekick.Web/Pages/_Host.cshtml
  src/Sidekick.Wpf/wwwroot/index.html
Labels: Type: Maintenance

#723 Enable context menu in debug mode for Linux version
  src/Sidekick.PhotinoBlazor/Program.cs
Labels: Type: Maintenance

#726 Application bar in Linux version can now be dragged with the mouse
  src/Sidekick.Common.Platform/Keyboards/KeyboardProvider.cs
  src/Sidekick.Common.Ui/App/AppBar.razor
  src/Sidekick.Common.Ui/App/AppDragHandle.razor
  src/Sidekick.Common.Ui/Views/CurrentView.cs
  src/Sidekick.Common.Ui/Views/ICurrentView.cs
  src/Sidekick.Common/Platform/EventArgs/DraggedEventArgs.cs
  src/Sidekick.Common/Platform/IKeyboardProvider.cs
  src/Sidekick.Common/Platform/Input/ScrollWheelHandler.cs
  src/Sidekick.PhotinoBlazor/Program.cs
  src/Sidekick.PhotinoBlazor/Services/PhotinoBlazorApplicationService.cs
  src/Sidekick.PhotinoBlazor/SidekickPhotinoBlazorWrapper.razor
Labels: Type: Maintenance

#732 Updated keybinds to be more visually appealing in the settings
  src/Sidekick.Common.Blazor/Home/Home.razor
  src/Sidekick.Common.Blazor/Home/HomeResources.fr.resx
  src/Sidekick.Common.Blazor/Home/HomeResources.ko.resx
  src/Sidekick.Common.Blazor/Home/HomeResources.resx
  src/Sidekick.Common.Blazor/Settings/Components/KeybindDisplay.razor
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditor.razor
  src/Sidekick.Common.Blazor/Settings/Components/KeybindEditorInternal.razor
  src/Sidekick.Common.Blazor/Settings/Components/SettingCheckboxEditor.razor
  src/Sidekick.Common.Blazor/Settings/Components/TextWithKeybinds.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.fr.resx
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Modules.General/Localization/GeneralResources.fr.resx
  src/Sidekick.Modules.General/Localization/GeneralResources.resx
  src/Sidekick.Modules.General/Settings/Game/GameSettingsPage.razor
Labels: Type: Maintenance
