Repository Sidekick-Poe/Sidekick, pull requests merged in 2025-06, with the labels that each got.

#736 Limit the length of the log displayed if an unhandled crash occurs
  src/Sidekick.Wpf/Program.cs
Labels: Type: Maintenance

#737 Replace Hardcodet.NotifyIcon.Wpf by NotificationIcon.NET
  Directory.Packages.props
  src/Sidekick.Common/Localization/UiLanguageProvider.cs
  src/Sidekick.PhotinoBlazor/Services/PhotinoBlazorApplicationService.cs
  src/Sidekick.Wpf/Helpers/CenterHelper.cs
  src/Sidekick.Wpf/Services/SimpleCommand.cs
  src/Sidekick.Wpf/Services/WpfApplicationService.cs
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
Labels: Type: Maintenance

#738 Significantly speed up the initialization process
  src/Sidekick.Common.Blazor/Initialization/Initialization.razor.cs
Labels: Type: Maintenance

#742 Change Pseudo parser priority order during initialization
  src/Sidekick.Apis.Poe.Trade/Parser/Pseudo/PseudoParser.cs
Labels: Type: Bug

#744 Improved performance of some UI components
  .gitignore
  src/Sidekick.Common.Ui/App/AppWrapper.razor
  src/Sidekick.Common.Ui/Popovers/Popover.razor
  src/Sidekick.Common.Ui/Popovers/PopoverTrigger.cs
  src/Sidekick.Common.Ui/Scripts/esbuild.js
  src/Sidekick.Common.Ui/Scripts/flowbite/popover.js
  src/Sidekick.Common.Ui/Scripts/flowbite/tooltip.js
  src/Sidekick.Common.Ui/Scripts/index.js
  src/Sidekick.Common.Ui/Sidekick.Common.Ui.csproj
  src/Sidekick.Common.Ui/Tooltips/Tooltip.razor
  src/Sidekick.Common.Ui/UiUtilities.cs
  src/Sidekick.Common.Ui/Utilities/FlowbiteComponent.cs
  src/Sidekick.Common.Ui/Utilities/FlowbiteComponent.razor
  src/Sidekick.Common.Ui/package-lock.json
  src/Sidekick.Common.Ui/package.json
  src/Sidekick.Common.Ui/wwwroot/js/donotdelete.txt
  src/Sidekick.Modules.Trade/Components/Options/ItemOptions.razor
  src/Sidekick.Modules.Trade/Components/Options/OpenWebsiteLink.razor
  src/Sidekick.PhotinoBlazor/wwwroot/index.html
  src/Sidekick.Web/Pages/_Host.cshtml
  src/Sidekick.Wpf/wwwroot/index.html
Labels: Type: Maintenance

#747 Fix poe.ninja open in website link
  src/Sidekick.Apis.Poe.Trade/Parser/Modifiers/ModifierParser.cs
  src/Sidekick.Apis.PoeNinja/Models/NinjaEconomyLeague.cs
  src/Sidekick.Apis.PoeNinja/Models/NinjaIndexState.cs
  src/Sidekick.Apis.PoeNinja/PoeNinjaClient.cs
Labels: Type: Bug

#749 Improved modifier filters to use the average value.
  src/Sidekick.Apis.Poe.Trade/Parser/AdditionalInformation/ClusterJewelParser.cs
  src/Sidekick.Apis.Poe.Trade/Parser/Modifiers/ModifierParser.cs
  src/Sidekick.Apis.Poe.Trade/Parser/Pseudo/PseudoDefinition.cs
  src/Sidekick.Apis.Poe.Trade/Trade/Filters/ModifierFilter.cs
  src/Sidekick.Common/Game/Items/ModifierLine.cs
Labels: Type: Enhancement
