Repository Sidekick-Poe/Sidekick, pull requests merged in 2025-03, with the labels that each got.

#563 Remove services from initialization
  src/Sidekick.Apis.Poe/Parser/Requirements/IRequirementsParser.cs
  src/Sidekick.Apis.Poe/Parser/Requirements/RequirementsParser.cs
  src/Sidekick.Apis.Poe/Parser/Sockets/ISocketParser.cs
  src/Sidekick.Apis.Poe/Parser/Sockets/SocketParser.cs
  src/Sidekick.Apis.Poe/StartupExtensions.cs
Labels: Type: Maintenance

#565 Create HttpClients as they are needed
  src/Sidekick.Apis.Poe/Authentication/AuthenticationService.cs
  src/Sidekick.Apis.Poe/Bulk/BulkTradeService.cs
  src/Sidekick.Apis.Poe/Clients/PoeApiClient.cs
  src/Sidekick.Apis.Poe/Clients/PoeTradeClient.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
Labels: Type: Maintenance

#567 Add setting whether to automatically search when price checking
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.Trade/PriceCheckService.cs
  src/Sidekick.Modules.Trade/Settings/PriceCheckAutomaticallySearchEditor.razor
  src/Sidekick.Modules.Trade/Settings/SettingsContent.razor
Labels: Type: Enhancement

#569 Refactor TryParse-methods to use NotNullWhenAttribute
  src/Sidekick.Apis.Poe/Parser/AdditionalInformation/ClusterJewelParser.cs
  src/Sidekick.Apis.Poe/Parser/ParsingBlock.cs
  src/Sidekick.Apis.Poe/Parser/ParsingItem.cs
Labels: Type: Maintenance

#574 Fixed gem results not being displayed
  src/Sidekick.Apis.Poe/Trade/Results/ResultItem.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
Labels: Type: Bug

#568 Add a setting for default filter type
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/FilterType.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Modules.Trade/Components/Filters/FilterRange.razor
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/DoublePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/IntPropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/WeaponDamagePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/PseudoFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/PseudoFiltersComponent.razor
  src/Sidekick.Modules.Trade/Localization/TradeResources.resx
  src/Sidekick.Modules.Trade/Settings/PriceCheckDefaultFilterTypeEditor.razor
  src/Sidekick.Modules.Trade/Settings/SettingsContent.razor
Labels: Type: Enhancement

#576 Make JsonSerializerOptions static
  src/Sidekick.Apis.GitHub/GitHubClient.cs
  src/Sidekick.Apis.Poe/Bulk/BulkTradeService.cs
  src/Sidekick.Apis.Poe/Clients/IPoeTradeClient.cs
  src/Sidekick.Apis.Poe/Clients/PoeApiClient.cs
  src/Sidekick.Apis.Poe/Clients/PoeTradeClient.cs
  src/Sidekick.Apis.Poe/Clients/PoeTradeHandler.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Apis.PoeNinja/PoeNinjaClient.cs
  src/Sidekick.Apis.PoePriceInfo/PoePriceInfoClient.cs
  src/Sidekick.Apis.PoeWiki/PoeWikiClient.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/ParserFixture.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Query/TradeSearchServiceTests.cs
Labels: Type: Maintenance

#577 Dispose disposables
  .editorconfig
  src/Sidekick.Apis.Poe/Authentication/AuthenticationService.cs
  src/Sidekick.Apis.Poe/Bulk/BulkTradeService.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common.Platform/GameLogs/GameLogProvider.cs
  src/Sidekick.Common.Ui/Views/ViewPreferenceService.cs
  src/Sidekick.Common/Folder/FolderProvider.cs
  src/Sidekick.Common/Logging/LogSink.cs
Labels: Type: Maintenance

#575 Refactor initialization of Item
  src/Sidekick.Apis.Poe/Parser/AdditionalInformation/ClusterJewelParser.cs
  src/Sidekick.Apis.Poe/Parser/ItemParser.cs
  src/Sidekick.Apis.Poe/Trade/Models/TradeItem.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common/Game/Items/Item.cs
Labels: Type: Maintenance

#581 Reduce Services to be Initialized
  src/Sidekick.Common/Game/Languages/GameLanguageProvider.cs
  src/Sidekick.Common/ServiceCollectionExtensions.cs
  src/Sidekick.Common/Settings/ISettingsService.cs
  src/Sidekick.Common/Settings/SettingsService.cs
Labels: Type: Maintenance

#583 Improved filter number input controls
  src/Sidekick.Common.Ui/Forms/FormContentEditable.razor
  src/Sidekick.Common.Ui/Forms/FormContentEditable.razor.js
  src/Sidekick.Modules.Trade/Components/Filters/FilterRange.razor
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFilterComponent.razor
  src/Sidekick.Wpf/Services/WpfViewLocator.cs
Labels: Type: Enhancement

#588 Updated .NET version
  .github/workflows/tests.yml
  .github/workflows/windows-beta.yml
  .github/workflows/windows-stable.yml
  .run/Publish Sidekick.Protocol to Sidekick.Wpf.run.xml
  .run/Sidekick.Web.run.xml
  .run/Sidekick.Wpf.run.xml
  Dockerfile
  src/Sidekick.Apis.GitHub/Sidekick.Apis.GitHub.csproj
  src/Sidekick.Apis.Poe/Sidekick.Apis.Poe.csproj
  src/Sidekick.Apis.PoeNinja/Sidekick.Apis.PoeNinja.csproj
  src/Sidekick.Apis.PoePriceInfo/Sidekick.Apis.PoePriceInfo.csproj
  src/Sidekick.Apis.PoeWiki/Sidekick.Apis.PoeWiki.csproj
  src/Sidekick.Common.Blazor/Main.razor
  src/Sidekick.Common.Blazor/Sidekick.Common.Blazor.csproj
  src/Sidekick.Common.Database/Sidekick.Common.Database.csproj
  src/Sidekick.Common.Interprocess/Sidekick.Common.Interprocess.csproj
  src/Sidekick.Common.Platform/Sidekick.Common.Platform.csproj
  src/Sidekick.Common.Ui/Sidekick.Common.Ui.csproj
  src/Sidekick.Common.Updater/Sidekick.Common.Updater.csproj
  src/Sidekick.Common/Sidekick.Common.csproj
  src/Sidekick.Modules.Chat/Sidekick.Modules.Chat.csproj
  src/Sidekick.Modules.General/Sidekick.Modules.General.csproj
  src/Sidekick.Modules.Maps/Sidekick.Modules.Maps.csproj
  src/Sidekick.Modules.Trade/Sidekick.Modules.Trade.csproj
  src/Sidekick.Modules.Wealth/Sidekick.Modules.Wealth.csproj
  src/Sidekick.Protocol/Properties/PublishProfiles/Build.pubxml
  src/Sidekick.Protocol/Sidekick.Protocol.csproj
  src/Sidekick.Web/Sidekick.Web.csproj
  src/Sidekick.Wpf/Properties/PublishProfiles/ClickOnceBeta.pubxml
  src/Sidekick.Wpf/Properties/PublishProfiles/ClickOnceRelease.pubxml
  src/Sidekick.Wpf/Sidekick.Wpf.csproj
  tests/Sidekick.Apis.Poe.Tests/Sidekick.Apis.Poe.Tests.csproj
Labels: Type: Maintenance

#589 Add PoE2 item header visuals
  src/Sidekick.Common.Ui/Poe/Items/ItemHeader.razor
  src/Sidekick.Common.Ui/Styles/item-headers.css
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-currency-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-currency-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-currency-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-rare-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-rare-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-rare-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-unique-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-unique-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-double-unique-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-gem-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-gem-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-gem-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-magic-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-magic-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-magic-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-normal-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-normal-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-normal-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-rare-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-rare-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-rare-right.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-unique-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-unique-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/poe2/header-unique-right.png
  src/Sidekick.Modules.Maps/MapOverlay.razor
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemComponent.razor
Labels: Type: Enhancement

#590 Improved expedition logbook support
  src/Sidekick.Apis.Poe/Fuzzy/FuzzyService.cs
  src/Sidekick.Apis.Poe/ITradeSearchService.cs
  src/Sidekick.Apis.Poe/Modifiers/IModifierProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/Models/ModifierDefinition.cs
  src/Sidekick.Apis.Poe/Modifiers/Models/ModifierMatch.cs
  src/Sidekick.Apis.Poe/Modifiers/Models/ModifierPattern.cs
  src/Sidekick.Apis.Poe/Modifiers/ModifierProvider.cs
  src/Sidekick.Apis.Poe/Parser/AdditionalInformation/ClusterJewelParser.cs
  src/Sidekick.Apis.Poe/Parser/Modifiers/ModifierMatch.cs
  src/Sidekick.Apis.Poe/Parser/Modifiers/ModifierParser.cs
  src/Sidekick.Apis.Poe/Parser/ParsingBlock.cs
  src/Sidekick.Apis.Poe/Parser/ParsingItem.cs
  src/Sidekick.Apis.Poe/Parser/ParsingLine.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemQuantityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemRarityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/MonsterPackSizeProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/WeaponDamageProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyParser.cs
  src/Sidekick.Apis.Poe/Parser/Pseudo/PseudoDefinition.cs
  src/Sidekick.Apis.Poe/Parser/Pseudo/PseudoParser.cs
  src/Sidekick.Apis.Poe/Trade/Results/Faction.cs
  src/Sidekick.Apis.Poe/Trade/Results/LogbookMod.cs
  src/Sidekick.Apis.Poe/Trade/Results/Result.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common.Ui/Poe/Items/ItemModifierText.razor
  src/Sidekick.Common.Ui/Poe/Items/ItemPropertyText.razor
  src/Sidekick.Common.Ui/Styles/item-headers.css
  src/Sidekick.Common.Ui/Styles/item-logbook-factions.css
  src/Sidekick.Common.Ui/Styles/main.css
  src/Sidekick.Common.Ui/wwwroot/images/items/expedition.png
  src/Sidekick.Common/Game/Items/Modifier.cs
  src/Sidekick.Common/Game/Items/ModifierCategory.cs
  src/Sidekick.Common/Game/Items/ModifierLine.cs
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemLineContentsComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemModifierLineComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemRequirements.razor
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/ExpeditionParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Query/TradeSearchServiceTests.cs
Labels: Type: Enhancement

#591 Improved modifier parsing accuracy
  src/Sidekick.Apis.Poe/Modifiers/Models/ModifierDefinition.cs
  src/Sidekick.Apis.Poe/Modifiers/ModifierProvider.cs
  src/Sidekick.Apis.Poe/Parser/Modifiers/ModifierParser.cs
  src/Sidekick.Apis.Poe/Trade/Models/LineContentValue.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Modules.Trade/Components/Bulk/BulkResult.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemsResult.razor
  src/Sidekick.Modules.Trade/PriceCheckService.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/FlaskParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/JewelParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/WeaponParsing.cs
Labels: Type: Enhancement

#592 Added Spirit property support
  Game Localization.xlsm
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/SpiritProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyParser.cs
  src/Sidekick.Apis.Poe/Trade/Requests/Filters/EquipmentFilters.cs
  src/Sidekick.Common/Game/Items/ItemProperties.cs
  src/Sidekick.Common/Game/Languages/IGameLanguage.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageDe.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEn.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEs.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageFr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageJp.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageKr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguagePt.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageRu.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageTh.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageZhTw.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/WeaponParsing.cs
Labels: Type: Enhancement

#593 Added support for Valdo rewards. Added foil item results styling.
  Game Localization.xlsm
  src/Sidekick.Apis.Poe/Items/ApiItemProvider.cs
  src/Sidekick.Apis.Poe/Items/IApiItemProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/IInvariantModifierProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/InvariantModifierProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/ModifierProvider.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/RewardProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Filters/StringPropertyFilter.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyDefinition.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyParser.cs
  src/Sidekick.Apis.Poe/Parser/RegexExtensions.cs
  src/Sidekick.Apis.Poe/Trade/Models/LineContentType.cs
  src/Sidekick.Apis.Poe/Trade/Models/LineContentTypeExtensions.cs
  src/Sidekick.Apis.Poe/Trade/Requests/Filters/MapFilters.cs
  src/Sidekick.Apis.Poe/Trade/Results/ResultItem.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common.Ui/Poe/Items/ItemHeader.razor
  src/Sidekick.Common.Ui/Styles/item-headers.css
  src/Sidekick.Common.Ui/wwwroot/images/items/header-double-foil-left.png
  src/Sidekick.Common.Ui/wwwroot/images/items/header-double-foil-middle.png
  src/Sidekick.Common.Ui/wwwroot/images/items/header-double-foil-right.png
  src/Sidekick.Common/Game/Items/ItemProperties.cs
  src/Sidekick.Common/Game/Items/Rarity.cs
  src/Sidekick.Common/Game/Languages/IGameLanguage.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageDe.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEn.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageEs.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageFr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageJp.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageKr.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguagePt.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageRu.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageTh.cs
  src/Sidekick.Common/Game/Languages/Implementations/GameLanguageZhTw.cs
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/StringPropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemLineContentsComponent.razor
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/MapParsing.cs
Labels: Type: Enhancement

#594 Adjusted colouring of augmented properties
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ArmourProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/AttacksPerSecondProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/BlockChanceProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/CriticalHitChanceProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/EnergyShieldProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/EvasionRatingProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemQuantityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemRarityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/MonsterPackSizeProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/QualityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/SpiritProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/WeaponDamageProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Filters/BooleanPropertyFilter.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Filters/StringPropertyFilter.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyDefinition.cs
  src/Sidekick.Apis.Poe/Parser/Properties/PropertyParser.cs
  src/Sidekick.Apis.Poe/Parser/RegexExtensions.cs
  src/Sidekick.Common/Game/Items/ItemProperties.cs
  src/Sidekick.Modules.Trade/Components/Filters/Properties/BooleanPropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/DoublePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/IntPropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/TriStatePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/WeaponDamagePropertyFilterComponent.razor
Labels: Type: Enhancement

#595 Refactored trade item results handling
  src/Sidekick.Apis.Poe/ITradeFilterService.cs
  src/Sidekick.Apis.Poe/ITradeSearchService.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ArmourProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/AttacksPerSecondProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/BlockChanceProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/CriticalHitChanceProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/EnergyShieldProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/EvasionRatingProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemQuantityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/ItemRarityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/MonsterPackSizeProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/QualityProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/RewardProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/SpiritProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Definitions/WeaponDamageProperty.cs
  src/Sidekick.Apis.Poe/Parser/Properties/Filters/BooleanPropertyFilter.cs
  src/Sidekick.Apis.Poe/Trade/Filters/ITradeFilter.cs
  src/Sidekick.Apis.Poe/Trade/Filters/ModifierFilter.cs
  src/Sidekick.Apis.Poe/Trade/Filters/PseudoModifierFilter.cs
  src/Sidekick.Apis.Poe/Trade/Models/FilterValueType.cs
  src/Sidekick.Apis.Poe/Trade/Models/LineContent.cs
  src/Sidekick.Apis.Poe/Trade/Models/LineContentValue.cs
  src/Sidekick.Apis.Poe/Trade/Models/TradeItem.cs
  src/Sidekick.Apis.Poe/Trade/Models/TradePrice.cs
  src/Sidekick.Apis.Poe/Trade/Requests/Filters/StatFilterValue.cs
  src/Sidekick.Apis.Poe/Trade/Results/LineContentType.cs
  src/Sidekick.Apis.Poe/Trade/Results/LineContentTypeExtensions.cs
  src/Sidekick.Apis.Poe/Trade/Results/Listing.cs
  src/Sidekick.Apis.Poe/Trade/Results/TradeItem.cs
  src/Sidekick.Apis.Poe/Trade/Results/TradeResult.cs
  src/Sidekick.Apis.Poe/Trade/TradeFilterService.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common.Blazor/Settings/General/LeagueIdEditor.razor
  src/Sidekick.Common.Ui/Poe/Items/ItemPropertyText.razor
  src/Sidekick.Common/Game/Items/Item.cs
  src/Sidekick.Common/Game/Items/ItemProperties.cs
  src/Sidekick.Common/Game/Items/Modifier.cs
  src/Sidekick.Common/Game/Items/ModifierLine.cs
  src/Sidekick.Modules.Trade/Components/Bulk/BulkResult.razor
  src/Sidekick.Modules.Trade/Components/Filters/FiltersComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/ModifierFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/Properties/WeaponDamagePropertyFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Filters/PseudoFilterComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemGemSocketsComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemImageComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemLineContentsComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemModifierLineComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemModifiers.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemProperties.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemRequirements.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemSocketsComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemsResult.razor
  src/Sidekick.Modules.Trade/Components/Options/OpenWebsiteLink.razor
  src/Sidekick.Modules.Trade/PriceCheckService.cs
  src/Sidekick.Modules.Trade/Prices.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckCurrencyModeEditor.razor
  src/Sidekick.Modules.Trade/Settings/PriceCheckNormalizeValueEditor.razor
  src/Sidekick.Modules.Trade/TradeMode.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Query/TradeSearchServiceTests.cs
Labels: Type: Maintenance

#602 Added properties at maximum quality in the trade results
  src/Sidekick.Apis.Poe/Trade/Results/Extended.cs
  src/Sidekick.Modules.Trade/Components/Items/ExtendedAtMax.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemComponent.razor
Labels: Type: Enhancement

#603 Added 'Grants Skill' line in the trade item results
  src/Sidekick.Apis.Poe/Trade/Results/LineContentType.cs
  src/Sidekick.Apis.Poe/Trade/Results/LineContentTypeExtensions.cs
  src/Sidekick.Apis.Poe/Trade/Results/ResultLineContent.cs
  src/Sidekick.Apis.Poe/Trade/Results/TradeItem.cs
  src/Sidekick.Modules.Trade/Components/Items/ItemComponent.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemGrantSkills.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemLineContentsComponent.razor
Labels: Type: Enhancement

#604 Fixed an uncaught exception when checking if Path of Exile is running as admin
  src/Sidekick.Common.Platform/Windows/Processes/ProcessProvider.cs
Labels: Type: Bug

#605 Adjusted positioning of Base Percentile in trade item results
  src/Sidekick.Modules.Trade/Components/Items/ExtendedAtMax.razor
  src/Sidekick.Modules.Trade/Components/Items/ItemProperties.razor
Labels: Type: Maintenance

#606 Update the version of SharpHook
  src/Sidekick.Common.Platform/Sidekick.Common.Platform.csproj
Labels: Type: Maintenance

#607 Implemented a zoom setting for large DPI displays
  src/Sidekick.Common.Blazor/Main.razor
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Blazor/Settings/General/ZoomEditor.razor
  src/Sidekick.Common.Blazor/Settings/SettingsResources.resx
  src/Sidekick.Common.Ui/App/AppWrapper.razor
  src/Sidekick.Common.Ui/App/AppWrapper.razor.js
  src/Sidekick.Common.Ui/Forms/FormContentEditable.razor
  src/Sidekick.Common.Ui/Styles/main.css
  src/Sidekick.Common/Settings/DefaultSettings.cs
  src/Sidekick.Common/Settings/SettingKeys.cs
  src/Sidekick.Common/Settings/SettingsService.cs
  src/Sidekick.Wpf/MainWindow.xaml.cs
Labels: Type: Enhancement

#608 Fixed overlays not opening consistently
  src/Sidekick.Apis.Poe/Parser/Headers/HeaderParser.cs
  src/Sidekick.Apis.Poe/Parser/Modifiers/ModifierParser.cs
  src/Sidekick.Apis.Poe/Trade/TradeSearchService.cs
  src/Sidekick.Common.Ui/Errors/SidekickErrorBoundary.razor
  src/Sidekick.Common/Game/Items/ItemHeader.cs
  src/Sidekick.Common/ServiceCollectionExtensions.cs
  src/Sidekick.Modules.Trade/Components/Filters/HeaderFilters.razor
  src/Sidekick.Wpf/SidekickBlazorWrapper.razor
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/AbyssParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/AscendancyParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/BeastParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/BetrayalParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/BlightParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/BodyArmourParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/BreachParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/ChargedCompassParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/DeliriumParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/DelveParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/DivinationCardParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/EssenceParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/ExpeditionParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/FlaskParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/GemParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/HeistParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/IdolParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/IncursionParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/JewelParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/MapParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/OrbParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/PantheonParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/RingParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/RitualParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/SanctumParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/UltimatumParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe1/Parser/WeaponParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/ArmourParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/CurrencyParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/FlaskParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/SanctumParsing.cs
  tests/Sidekick.Apis.Poe.Tests/Poe2/Parser/TabletParsing.cs
Labels: Type: Bug

#609 Allow the application to start even if the API is down
  src/Sidekick.Apis.Poe/Filters/FilterProvider.cs
  src/Sidekick.Apis.Poe/Items/ApiInvariantItemProvider.cs
  src/Sidekick.Apis.Poe/Items/ApiItemProvider.cs
  src/Sidekick.Apis.Poe/Leagues/LeagueProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/InvariantModifierProvider.cs
  src/Sidekick.Apis.Poe/Modifiers/ModifierProvider.cs
  src/Sidekick.Apis.Poe/Parser/Pseudo/PseudoParser.cs
  src/Sidekick.Apis.Poe/Static/ItemStaticDataProvider.cs
  src/Sidekick.Common.Blazor/Initialization/Initialization.razor.cs
  src/Sidekick.Common.Blazor/Settings/General/General.razor
  src/Sidekick.Common.Blazor/Setup/Setup.razor
  src/Sidekick.Common.Ui/App/AppResources.resx
  src/Sidekick.Common.Ui/Errors/ConfigurationFlagError.razor
  src/Sidekick.Common.Ui/Layouts/LayoutSimple.razor
  src/Sidekick.Common.Ui/Layouts/LayoutTwoColumn.razor
  src/Sidekick.Common/SidekickConfiguration.cs
  src/Sidekick.Wpf/Cloudflare/CloudflareWindow.xaml.cs
Labels: Type: Enhancement

#610 Fixed a crash when the application fails to open a browser
  src/Sidekick.Common.Platform/Clipboard/ClipboardProvider.cs
  src/Sidekick.Common/Browser/BrowserProvider.cs
Labels: Type: Bug
